# .sops.yaml
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - "age1lgme6wnqh43y87m2pvrx2yhe487lgs428xn7s67nxk9sr8d0nckssd0vp8"
          - "age1wl7kzsn6gmlvtsnteyzq0ehj53ggua6fperjfxpdgdxq89e00a8qcnsyxe"